import BuildLP_fosB
import Analysis
import pandas as pd

tot_sol= ['GLU6PDEHYDROG-RXN', 'DIOHBUTANONEPSYN-RXN', 'UDPGLCNACEPIM-RXN', 'NAD-KIN-RXN', 'NAG1P-URIDYLTRANS-RXN', '6PFRUCTPHOS-RXN', 'RIBOPHOSPHAT-RXN', 'RXN-12878', 'O-SUCCINYLBENZOATE-COA-LIG-RXN', '2.7.7.39-RXN', 'ALARACECAT-RXN', 'RXN0-723', 'ASPCARBTRANS-RXN', 'RIBOFLAVIN-SYN-RXN', 'UNDECAPRENYL-DIPHOSPHATASE-RXN',
          'ADENYLOSUCCINATE-SYNTHASE-RXN', 'TEICHOICSYN3-RXN', 'UDPNACETYLMURAMATEDEHYDROG-RXN', 'AMPSYN-RXN', 'SHIKIMATE-5-DEHYDROGENASE-RXN', 'RXN-14175', 'UDP-NACMURALA-GLU-LIG-RXN', 'ADOMET-DMK-METHYLTRANSFER-RXN', 'GAPOXNPHOSPHN-RXN', 'AICARSYN-RXN', 'ACETALD-DEHYDROG-RXN', 'IPPISOM-RXN', 'DALADALALIG-RXN',
          'RIBOSYLHOMOCYSTEINASE-RXN', 'ADENOSYLHOMOCYSTEINE-NUCLEOSIDASE-RXN', 'PPENTOMUT-RXN', 'ORNITHINE-GLU-AMINOTRANSFORASE-RXN', 'GLUTRACE-RXN', 'RXN66-555',
          'METHYLENETHFDEHYDROG-NADP-RXN', 'ACETYL-COA-ACETYLTRANSFER-RXN', 'NAPHTHOATE-SYN-RXN', 'RXN-14116', 'S-ADENMETSYN-RXN', '3-DEHYDROQUINATE-DEHYDRATASE-RXN', 'FPPSYN-RXN', 'DMK-RXN', 'F16ALDOLASE-RXN', 'GART-RXN', 'DIHYDROFOLATEREDUCT-RXN', 'AICARTRANSFORM-RXN', 'O-SUCCINYLBENZOATE-COA-SYN-RXN', 'PANTEPADENYLYLTRAN-RXN',
          'TEICHOICSYN2-RXN', '6PGLUCONOLACT-RXN', 'NICOTINATEPRIBOSYLTRANS-RXN', 'GPPSYN-RXN', 'AIRCARBOXY-RXN', 'ISOCHORSYN-RXN', 'FADSYN-RXN', 'GTP-CYCLOHYDRO-II-RXN', 'THYMIDYLATESYN-RXN', 'PRPPSYN-RXN', 'PYRUVFORMLY-RXN', 'RXN-11065', 'CDPKIN-RXN', '2-DEHYDROPANTOATE-REDUCT-RXN', 'DEOXYADENYLATE-KINASE-RXN', 'DIHYDROOROT-RXN', 'METHENYLTHFCYCLOHYDRO-RXN',
          'RXN0-7008', 'CHORISMATE-SYNTHASE-RXN', 'RIBOFLAVINSYNREDUC-RXN', 'RXN-10015', 'RXN-10017', 'DTMPKI-RXN', 'ASPDECARBOX-RXN', 'RXN-11832', 'FGAMSYN-RXN', 'DAHPSYN-RXN', 'SAICARSYN-RXN', 'RXN-8975', 'DTDPKIN-RXN', '6.3.2.7-RXN', '3-CH3-2-OXOBUTANOATE-OH-CH3-XFER-RXN', 'RXN0-745', 'URPHOS-RXN', 'IMPCYCLOHYDROLASE-RXN', 'RXN-5061',
          'NICONUCADENYLYLTRAN-RXN', 'UDPKIN-RXN', 'DEOXYGUANOSINE-KINASE-RXN', 'SHIKIMATE-KINASE-RXN', '2.3.1.157-RXN', '2.5.1.19-RXN', 'DEPHOSPHOCOAKIN-RXN', 'PHOSPHOMEVALONATE-KINASE-RXN', 'MEVALONATE-KINASE-RXN', 'RXN-8976', 'DURIDKI-RXN', 'GLUTAMATE-DEHYDROGENASE-RXN', 'GLYOHMETRANS-RXN', 'UDPNACETYLGLUCOSAMENOLPYRTRANS-RXN', 'RXN-8999', 'GUANYL-KIN-RXN', 'BRANCHED-CHAINAMINOTRANSFERVAL-RXN', 'IMP-DEHYDROG-RXN', 'UDP-NACMUR-ALA-LIG-RXN',
          'GLYRIBONUCSYN-RXN', 'GLUC1PURIDYLTRANS-RXN', 'PGLUCISOM-RXN', 'PRPPAMIDOTRANS-RXN', 'PYRROLINECARBDEHYDROG-RXN', 'ALANINE-DEHYDROGENASE-RXN', 'GMKALT-RXN', 'AIRS-RXN', 'ARGININE-DEIMINASE-RXN', 'DEOXYADENOSINE-KINASE-RXN', '6.3.2.10-RXN', 'NAD-SYNTH-NH3-RXN', 'XMPXAN-RXN', 'HOMOCYSMETB12-RXN', '2PGADEHYDRAT-RXN', 'RIBOFLAVINKIN-RXN',
          'LUMAZINESYN-RXN', '3-DEHYDROQUINATE-SYNTHASE-RXN', 'RXN-9310', 'RXN-9311', 'PANTOTHENATE-KIN-RXN', 'GLCNACPTRANS-RXN', 'OROPRIBTRANS-RXN', 'RIBOFLAVINSYNDEAM-RXN', 'RXN-12002', 'RXN-3341', 'XANTHOSINEPHOSPHORY-RXN', 'GDPKIN-RXN', 'PYRUVDEH-RXN', '2OXOGLUTARATEDEH-RXN', 'INORGPYROPHOSPHAT-RXN', 'MALIC-NADP-RXN',
          'DIPHOSPHOMEVALONTE-DECARBOXYLASE-RXN', 'GLUCOKIN-RXN', 'GLYCEROL-KIN-RXN', 'RXN-14971', 'RXN-14117', 'OROTPDECARB-RXN', '1.1.1.39-RXN', 'ADENYL-KIN-RXN', 'HYDROXYMETHYLGLUTARYL-COA-SYNTHASE-RXN', '2.5.1.64-RXN', 'P-PANTOCYSDECARB-RXN', 'RXN-14207', 'OROTATE-REDUCTASE-NADH-RXN', 'CYTIKIN-RXN',
          'GMP-SYN-NH3-RXN', 'L-ALPHA-ALANINE_AA_bm_tx', 'ARG_AA_bm_tx', 'L-ASPARTATE_AA_bm_tx', 'CYS_AA_bm_tx', 'GLN_AA_bm_tx', 'GLT_AA_bm_tx', 'GLY_AA_bm_tx', 'HIS_AA_bm_tx', 'ILE_AA_bm_tx', 'LEU_AA_bm_tx', 'LYS_AA_bm_tx', 'MET_AA_bm_tx', 'PHE_AA_bm_tx', 'PRO_AA_bm_tx', 'SER_AA_bm_tx', 'THR_AA_bm_tx',
          'TRP_AA_bm_tx', 'TYR_AA_bm_tx', 'VAL_AA_bm_tx', 'DATP_bm_tx', 'DCTP_bm_tx', 'DGTP_bm_tx', 'DTTP_bm_tx', 'ATP_bm_tx', 'CTP_bm_tx', 'GTP_bm_tx', 'UTP_bm_tx', 'DAG_bm_tx', 'PG_bm_tx', 'CL_bm_tx', 'LTA_bm_tx', 'GLC2-DAG_bm_tx', 'GLC-DAG_bm_tx', 'Menaquinone_bm_tx', 'PepGly_bm_tx', 'WTA-PG_bm_tx', 'glycogen_bm_tx', 'acCoA_bm_tx', 'succCoA_bm_tx', 'CoA_bm_tx', 'FAD_bm_tx', 'NAD_bm_tx', 'NADH_bm_tx', 'NADP_bm_tx', 'NADPH_bm_tx',
          'PIA1_bf_bm_tx', 'PIA2_bf_bm_tx', 'PIA3_bf_bm_tx', 'L-ALPHA-ALANINE_AA_mm_tx', 'CYS_AA_mm_tx', 'ARG_AA_mm_tx', 'L-ASPARTATE_AA_mm_tx', 'HIS_AA_mm_tx', 'ILE_AA_mm_tx', 'LEU_AA_mm_tx', 'LYS_AA_mm_tx', 'MET_AA_mm_tx', 'PHE_AA_mm_tx', 'PRO_AA_mm_tx', 'SER_AA_mm_tx', 'TRP_AA_mm_tx', 'TYR_AA_mm_tx', 'THR_AA_mm_tx', 'VAL_AA_mm_tx', 'GLC_mm_tx', 'OXYGEN-MOLECULE_tx', 'Pi_mm_tx', 'NIACINE_mm_tx',
          'ACET_bp_tx', 'CARBON-DIOXIDE_bp_tx', 'AMMONIUM_bp_tx', 'Autoinducer_bp_tx', 'ATPASE-RXN', 'ATPSYN-RXN', 'NADH-DEHYDROG-A-RXN', 'RXN-14107', 'CYTOCHROME-C-OXIDASE-RXN', 'GLUC1PADENYLTRANS-RXN', 'GLYCOGENSYN-RXN', 'PIA1_synth', 'PIA2_synth', 'PIA3_synth', 'Palmitate_synth',
          'PA_synth_NADPH', 'CDPDIGLYSYN-RXN', 'PHOSPHAGLYPSYN-RXN', 'PGPPHOSPHA-RXN', 'CARDIOLIPSYN-RXN', 'RXN-18014', 'RXN-18013', 'RXN-18039', 'RXN-18038', 'RXN-18037', 'RXN-15117', 'RXN-18035', 'RXN-18036', 'RXN-16648', 'RXN-8992', 'THREONINE-ALDOLASE-RXN', 'RXN-11295', 'RXN-11296', 'RXN-11297', 'RXN-11291', 'GLYCINE--TRNA-LIGASE-RXN', 'RXN-11339',
          'RIBITOL-5-PHOSPHATE-2-DEHYDROGENASE-RXN', 'RXN-18006', 'RXN-18007', 'RXN-18008', '2.4.1.53-RXN', 'RXN-18020', 'TRANS-RXN-314', '2.7.7.40-RXN', '6.1.1.13-RXN', 'RXN-18027', 'RXN8J2-1', 'RXN8J2-2', 'RXN8J2-3', 'FOSF_mm_tx', 'BACILLFOSF_tx', 'RXN-16037', 'CYTIDEAM2-RXN', 'DEOXYRIBOSE-P-ALD-RXN', 'URA-PHOSPH-RXN',
          'SUCCCOASYN-RXN', 'RIB5PISOM-RXN', 'FUMHYDR-RXN', '5.4.2.10-RXN', 'URIDINEKIN-RXN', '3PGAREARR-RXN', 'RXN66-532', 'DEOXYGUANPHOSPHOR-RXN', 'RXN-15740', 'GUANINE-DEAMINASE-RXN', 'DEOXYADENPHOSPHOR-RXN', 'RIBULP3EPIM-RXN', 'L-GLN-FRUCT-6-P-AMINOTRANS-RXN', 'ORNCARBAMTRANSFER-RXN', 'ACETATE--COA-LIGASE-ADP-FORMING-RXN', '2TRANSKETO-RXN', 'PHOSGLYPHOS-RXN', 'D-PPENTOMUT-RXN', 'GLUCOSAMINE-6-P-DEAMIN-RXN', 'RXN-14192', '1.1.1.34-RXN', 'WATER_tx', 'NA+_H+_tx', 'DIACYLGLYKIN-RXN',
          'DGDPKIN-RXN','DADPKIN-RXN', 'PYRUFLAVREDUCT-RXN', 'HYDROXYMETHYLGLUTARYL-COA-REDUCTASE-RXN','TRIOSEPISOMERIZATION-RXN', 'GLUTDEHYD-RXN', '2-OXOGLUTARATE-SYNTHASE-RXN', 'SUC_bp_tx']
sol1 = ['DGDPKIN-RXN', 'DADPKIN-RXN', 'PYRUFLAVREDUCT-RXN', 'HYDROXYMETHYLGLUTARYL-COA-REDUCTASE-RXN', 'TRIOSEPISOMERIZATION-RXN', 'GLUTDEHYD-RXN', '2-OXOGLUTARATE-SYNTHASE-RXN', 'SUC_bp_tx']
sol2 = ['RXN-12878', 'RXN-14207', 'RXN-14192', 'HYDROXYMETHYLGLUTARYL-COA-REDUCTASE-RXN', 'TRIOSEPISOMERIZATION-RXN', 'GLUTDEHYD-RXN', '2-OXOGLUTARATE-SYNTHASE-RXN', 'SUC_bp_tx']
sol3 = ['RXN-12878', 'DGDPKIN-RXN', 'DADPKIN-RXN', 'HYDROXYMETHYLGLUTARYL-COA-REDUCTASE-RXN', 'TRIOSEPISOMERIZATION-RXN', 'GLUTDEHYD-RXN', '2-OXOGLUTARATE-SYNTHASE-RXN', 'SUC_bp_tx']
sol4 = ['1.1.1.34-RXN', 'DGDPKIN-RXN', 'DADPKIN-RXN', 'PYRUFLAVREDUCT-RXN', 'TRIOSEPISOMERIZATION-RXN', 'GLUTDEHYD-RXN', '2-OXOGLUTARATE-SYNTHASE-RXN', 'SUC_bp_tx']
sol5 = ['RXN-12878', 'MALIC-NADP-RXN', 'RXN-14117', 'RXN-14207', 'ACETATE--COA-LIGASE-ADP-FORMING-RXN', 'RXN-14192', 'PYRUFLAVREDUCT-RXN', 'HYDROXYMETHYLGLUTARYL-COA-REDUCTASE-RXN']
sol6 = ['RXN-12878', 'MALIC-NADP-RXN', 'ACETATE--COA-LIGASE-ADP-FORMING-RXN', 'RXN-14192', 'DGDPKIN-RXN', 'PYRUFLAVREDUCT-RXN', 'HYDROXYMETHYLGLUTARYL-COA-REDUCTASE-RXN', 'TRIOSEPISOMERIZATION-RXN']
sol7 = ['RXN-12878', 'MALIC-NADP-RXN', '1.1.1.34-RXN', 'DGDPKIN-RXN', 'DADPKIN-RXN', 'PYRUFLAVREDUCT-RXN', 'TRIOSEPISOMERIZATION-RXN', 'SUC_bp_tx']
sol8 = ['RXN-12878', '1.1.1.39-RXN', 'RXN-14207', 'ACETATE--COA-LIGASE-ADP-FORMING-RXN', 'RXN-14192', 'PYRUFLAVREDUCT-RXN', 'HYDROXYMETHYLGLUTARYL-COA-REDUCTASE-RXN', 'TRIOSEPISOMERIZATION-RXN']

def switch(m):   #produce two solutions with or without fosfomycin uptake
    sol = solLP(m)
    sol1= solLP(m,cos={'FOSF_mm_tx':0.422}) #value for which the cysteine reaches 0.43 which is the max in the media
    Analysis.CompareSol(sol,sol1)
    
def solLP(m, cos=None): #main lp producing solution; can accept constraints
    lp=BuildLP_fosB.BoundedUptakeLP(m)
    if cos!=None:
        lp.SetFixedFlux(cos)
    lp.Solve()
    sol=lp.GetPrimSol()
    print(lp.GetObjVal())
    print(sol['CYS_AA_mm_tx'])
    lp.ClearFluxConstraints()
    return sol

    
def f_scan(m):
    lp=BuildLP_fosB.BoundedUptakeLP(m)
    Analysis.Scan(lp,'FOSF_mm_tx',upper=0.422,lower=0.007)
        
def f_max(m):
    lp=BuildLP_fosB.BoundedUptakeLP(m)
    sol1= solLP(m,cos={'FOSF_mm_tx':0.422})
    return sol1

def check_sol_fmax(m):
    sol = f_max(m)
    to_remove = tot_sol
    to_add = []
    for r in sol:
        if r not in tot_sol:
            to_add.append(r)
        else:
            to_remove.remove(r)

    if to_remove == sol1:
        print('this solution matches solution I')
    elif to_remove == sol2:
        print('this solution matches solution II')
    elif to_remove == sol3:
        print('this solution matches solution III')
    elif to_remove == sol4:
        print('this solution matches solution IV')
    elif to_remove == sol5:
        print('this solution matches solution V')
    elif to_remove == sol6:
        print('this solution matches solution VI')
    elif to_remove == sol7:
        print('this solution matches solution VII')
    elif to_remove == sol8:
        print('this solution matches solution VIII')
    else:
        print('add the following reactions')
        print(f'{to_add[:len(to_add)//2]}')
        print(f'{to_add[len(to_add)//2:]}')
        print('remove the following reactions')
        print(f'{to_remove}')

    
